Starting the script...
Loading model: qwen2-0.5B-Instruct
Gradient checkpointing enabled for qwen2-0.5B-Instruct
Gradient checkpointing enabled.
Loading tokenizer...
Tokenizer loaded successfully.
Loading Dataset...
Dataset loaded from results/datasets/qwen2-0.5B-Instruct_100.pkl
Successfully loaded dataset.
Starting SFT for 10 epochs...
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
/Users/vedantgaur/Projects/mech-interp-triggers/myenv/lib/python3.12/site-packages/torch/amp/grad_scaler.py:131: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn(
/Users/vedantgaur/Projects/mech-interp-triggers/myenv/lib/python3.12/site-packages/torch/amp/autocast_mode.py:250: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn(
Epoch 1/10, Average Loss: 0.879461317062378
Epoch 2/10, Average Loss: 0.39136108160018923
Epoch 3/10, Average Loss: 0.2115514534711838
Epoch 4/10, Average Loss: 0.12303379714488984
Epoch 5/10, Average Loss: 0.07369649603962898
Epoch 6/10, Average Loss: 0.051728353798389436
Epoch 7/10, Average Loss: 0.04144386887550354
Epoch 8/10, Average Loss: 0.032296384647488595
Epoch 9/10, Average Loss: 0.02667532838881016
Epoch 10/10, Average Loss: 0.022614328525960445
Supervised fine-tuning completed.
/Users/vedantgaur/Projects/mech-interp-triggers/myenv/lib/python3.12/site-packages/torch/utils/checkpoint.py:91: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
Preparing classification dataset...
Traceback (most recent call last):
  File "/Users/vedantgaur/Projects/mech-interp-triggers/scripts/train.py", line 126, in <module>
    main(args)
  File "/Users/vedantgaur/Projects/mech-interp-triggers/scripts/train.py", line 104, in main
    dataset = load_dataset(f"results/datasets/test_{args.model}_{args.dataset_size}.pkl")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vedantgaur/Projects/mech-interp-triggers/src/data/dataset_generator.py", line 90, in load_dataset
    with open(file_path, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'results/datasets/test_qwen2-0.5B-Instruct_100.pkl'
Classifier dataset size: 12 samples
Classification dataset prepared. Input size: 896
Initializing and training classifier...
Classifier Epoch 1/10, Loss: 1.1764928307384253
Classifier Epoch 2/10, Loss: 0.5206121128673354
Classifier Epoch 3/10, Loss: 0.4640426555027564
Classifier Epoch 4/10, Loss: 0.4060103438872223
Classifier Epoch 5/10, Loss: 0.22879332928763083
Classifier Epoch 6/10, Loss: 0.143848010028402
Classifier Epoch 7/10, Loss: 0.06284598835433523
Classifier Epoch 8/10, Loss: 0.04459494476517042
Classifier Epoch 9/10, Loss: 0.033595367606418826
Classifier Epoch 10/10, Loss: 0.025759218687502045
Classifier training completed.
Starting evaluation...
Loading Dataset...